services:
  collector:
    image: evidently/evidently-service:0.4.33
    entrypoint: ["evidently", "collector"]
    command: ["--config-path", "/config/collector.json"]
    ports:
      - 8001:8001
    volumes:
      - ./config:/config

  ui:
    image: evidently/evidently-service:0.4.33
    ports:
      - 8000:8000
    command: ["--workspace", "/data"]
    volumes:
      - data:/data
volumes:
  data:
