version: '3.8'

services:
  app:
    image: 493395458839.dkr.ecr.us-east-1.amazonaws.com/dataphoenix-writer-agent:latest
    container_name: news-agency-app
    restart: always
    ports:
      - "5001:5000"
    env_file:
      - docker.env
    depends_on:
      - db
    volumes:
      - ./docker.env:/app/.env

  db:
    image: postgres:15-alpine
    container_name: news-agency-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=news_agency
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
